update stack and bucket name

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -130,20 +130,18 @@ ENV_DIR=$3
 
 # fix STACK variable if unset
 if [[ -z "${STACK}" ]]; then
-  STACK="heroku-16"
+  STACK="heroku-18"
 fi
 
 # ensure correct stack
-if [[ ! "$STACK" == "heroku-16" ]]; then
-
+if [[ ! "$STACK" == "heroku-18" ]]; then
   echo
-  echo "-----> ERROR: This version of the buildpack is intended for use with the 'heroku-16' stack"
+  echo "-----> ERROR: This version of the buildpack is intended for use with the 'heroku-18' stack"
   echo
-  echo "       Use the 'heroku stack:set' CLI command to use the 'heroku-16' stack."
+  echo "       Use the 'heroku stack:set' CLI command to use the 'heroku-18' stack."
   echo "       See https://devcenter.heroku.com/articles/stack for more information."
   echo
   exit 1
-
 fi
 
 # read in R version if file exists
@@ -151,7 +149,10 @@ if [[ -f "$BUILD_DIR/.r-version" ]]; then
   R_VERSION=$(read_var "$BUILD_DIR/.r-version")
   echo "NOTE: Using R version override [$R_VERSION]" | indent
 else
-  R_VERSION="3.4.3"
+  echo
+  echo "-----> ERROR: You must set a specific R version in /.r-version"
+  echo
+  exit 1
 fi
 
 # environment
@@ -167,7 +168,7 @@ export PATH="$FAKECHROOT_DIR/sbin:$FAKECHROOT_DIR/bin:/usr/local/sbin:/usr/local
 export_env_dir "$ENV_DIR"
 
 # S3 bucket, cran mirror, buildpack version can be set via environment
-S3_BUCKET=${S3_BUCKET:-"heroku-buildpack-r"}
+S3_BUCKET=${S3_BUCKET:-"heroku-r-buildpack"}
 CRAN_MIRROR=${CRAN_MIRROR:-"https://cloud.r-project.org"}
 BUILD_PACK_VERSION=${BUILD_PACK_VERSION:-latest}
 
